# Generated by Django 5.2.7 on 2025-11-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='citadental',
            name='procedimiento',
        ),
        migrations.AddField(
            model_name='citadental',
            name='tratamientos',
            field=models.ManyToManyField(blank=True, help_text='Tratamientos asociados a la cita', related_name='citas', to='app.tratamiento'),
        ),
    ]
